Traceback (most recent call last):
  File "/home/janulm/janulm_agent_nodes/agent-net/ogb_arxiv.py", line 218, in <module>
    #print(results)
IndexError: index 1443 is out of bounds for axis 0 with size 3
