Traceback (most recent call last):
  File "/home/janulm/janulm_agent_nodes/traditional_gcn/gcn_cora.py", line 165, in <module>
    print("max result test acc: ",results[np.argmax(results)],np.argmax(results))
IndexError: index 46 is out of bounds for axis 0 with size 3
